### PR TITLE
Fix a bunch of bugs and improve Linux compatibility.

### PR DESCRIPTION
**Pull request by maksverver**

### CODE REVIEW

**Comment by droe** [comment]
Ah, reading your commits is like a walk of shame into the past :)

Thanks for your fixes. I like everything except 827a24e:

-   The code deliberately did the XOR and the memory write in one go in order to only write the data only once
-   The XOR operations were deliberately in 64 bit quantities, not bytewise
-   I fail to see any strict aliasing violations in the code you replaced, but maybe I am overlooking something

Can you back out 827a24e of this pull req? Then I will merge it.

**Comment by maksverver** [comment]
Sorry, I'm a bit of Github noob. I created a separate pull request, that excludes 827a24e (I think). Could you try merging that one and rejecting this?

Re: strict aliasing: I think all code like this:

    char buf[8];
    *(int64_t*)buf = 123;

... are strict-aliasing violations, because you're accessing an object through a pointer of a different type. The other way around (accessing an int64_t through an (unsigned) char*) is allowed, though, which is why the fix in 66a5b11 works.

Re: xor'ing bytes, do you object to that for performance reasons? I was hoping the compiler would be able to optimize the rose_xor_block() function so that it doesn't need to xor a byte at a time. For example, see: https://godbolt.org/g/4QxF7G (that even uses an MMX instruction to xor 128 bits at a time!)

So it might not actually cost you anything in terms of performance (and that's assuming the xor part is significant compared to the AES encryption).

**Comment by droe** [comment]
Note that char pointers are always allowed under strict aliasing rules. Also note that access using different but compatible pointer types is also allowed.

Yes, the quantities are about performance; I like to believe it makes sense to optimize crypto loops a little where it is easy to do. Smart compilers can still optimize it while dumb compilers benefit. Granted, that's like gcc 2 era thinking which may actually be obsolete these days. Switch the compiler to gcc 4 on that compiler explorer to see where I'm coming from when I prefer larger quantities.

The separate branch is exactly the way to go. Will merge that in a minute. Closing this pull req.

**Comment by maksverver** [comment]
> Note that char pointers are always allowed under strict aliasing rules. Also note that access using different but compatible pointer types is also allowed.

I think that only works in one direction: you can access an `int` through a `char*`, but not a char array through an `int*`. I found this answer on StackOverflow that contains the exact wording from the standard: http://stackoverflow.com/a/7005988

Here's a minimal example of such an error: https://godbolt.org/g/4lRcG2

If I rewrite parts of rosefs.c, depending on the exact expression, the compiler sometimes detects the violation. For example, if I rewrite the main loop from rose_ctr_crypt() like this:

    while (i + AES_BLOCK_SIZE <= sz) {
      AES_encrypt((unsigned char*)block, keystream, key);
      block[0]++;
      *(uint64_t*)(dst+i) = *(uint64_t*)(src+i) ^ *(uint64_t*)(keystream);
      *(uint64_t*)(dst+i) = *(uint64_t*)(src+i) ^ *(uint64_t*)(keystream + 8);
      i += 16;
    }

... it triggers a warning (which is treated as an error because CFLAGS contains -Werror). Of course, even if the compiler doesn't emit a warning, the violation is still there. So to be on the safe side, I feel like I either have to get rid of these aliasing problems or compile with -fno-strict-aliasing to prevent the compiler from getting the wrong idea.

**Pull request closed without merging**
